INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, EMAIL)
VALUES (1, 'Shadab', 'Khan', 'shadabkhan', 'password', 'shadab.khan@callsign.com');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, EMAIL)
VALUES (2, 'Abrar', 'Siddiqui', 'abrarsiddiqui', 'password', 'abrar.Siddiqui@callsign.com');

INSERT INTO ROLE (ID, NAME)
VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLE (ID, NAME)
VALUES (2, 'ROLE_SUPPORT');

INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES (1, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES (1, 2);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES (2, 2);


